### PR TITLE
Use PyCryptodome

### PR DESCRIPTION
**Pull request by bit**
Use PyCryptodome instead of PyCrypto

- remove Counter
- sing/verify with long values instead of bytes using _ functions

#68

### CODE REVIEW

**Comment by koolfy** [comment]
Hello, I saw this PR in my emails 2 months ago and honestly dragged a bit because it was going to be  some small changes to code I almost lost hope for.

But… from the looks of it you might have finished the pycryptodome transition I was working on for years and was stuck at because of some pycryptodome limitation o___o

I'll pay very close attention to this PR in the coming days, test it out, see what I missed on my side, what changed on pycryptodome since I last attempted to do exactly what you did, etc!

Check this for context of how much alcoholic/sugary beverage of your choice I will forever owe you if this turns out to put the project back on rails: https://github.com/python-otr/pure-python-otr/issues/68

Huge thanks!!!

**Comment by bit** [comment]
Would be great to see it merged and always happy to meet for drinks.
I had to rework your use of the Counter and call the _sign function in PyCryptodome to get low level enough access to the signing primitives. With that the change was manageable.

**Comment by koolfy** [comment]
Solved some quick conflicts, I'm merging into the dedicated pycryptodome branch, I'll test it out some more there and merge back into master and release if the merge makes sense (worst case scenario I just drop my previous pycryptodome branch and just use yours)

Then a quick release of a new major version and we should be good to go :)

**Comment by lanodan** [comment]
It looks like there is a slight issue, it is declared as depending on `PyCryptodome` (`Crypto` module) while it is importing the `Cryptodome` module (`pycryptodomex`). (See: <https://github.com/Legrandin/pycryptodome/blob/master/README.rst#pycryptodome>)

And I don't know for the other distros but it looks like only the `Crypto` module variant is available on Gentoo.

**Pull request merged**
